"""initial schema

Revision ID: cd0f2927ee5e
Revises: 
Create Date: 2025-12-05 18:20:02.035578+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd0f2927ee5e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email address (unique)'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Bcrypt hashed password'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='User role: player, developer, or admin'),
    sa.Column('display_name', sa.String(length=100), nullable=True, comment="User's display name"),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Account active status'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_role_active', 'users', ['role', 'is_active'], unique=False)
    op.create_table('cats',
    sa.Column('developer_id', sa.UUID(), nullable=False, comment='Cat developer (FK to users.id)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Cat name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Cat description'),
    sa.Column('version', sa.String(length=20), nullable=True, comment='Semantic version (e.g., 1.0.0)'),
    sa.Column('endpoint_url', sa.String(length=500), nullable=False, comment='Cat API endpoint URL'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Cat status: draft, published, suspended'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['developer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cats_developer_status', 'cats', ['developer_id', 'status'], unique=False)
    op.create_index('ix_cats_status', 'cats', ['status'], unique=False)
    op.create_table('installations',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Cat owner (FK to users.id)'),
    sa.Column('cat_id', sa.UUID(), nullable=False, comment='Installed cat (FK to cats.id)'),
    sa.Column('instance_name', sa.String(length=100), nullable=True, comment='User-defined instance name'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Installation-specific configuration (JSON)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Installation status: active, paused, uninstalled'),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=False, comment='Installation timestamp (UTC)'),
    sa.Column('last_interaction_at', sa.DateTime(timezone=True), nullable=True, comment='Last usage timestamp (UTC)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['cat_id'], ['cats.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'cat_id', 'instance_name', name='uq_user_cat_instance')
    )
    op.create_index('ix_installations_last_interaction', 'installations', ['last_interaction_at'], unique=False)
    op.create_index('ix_installations_user_status', 'installations', ['user_id', 'status'], unique=False)
    op.create_table('permissions',
    sa.Column('cat_id', sa.UUID(), nullable=False, comment='Associated cat (FK to cats.id)'),
    sa.Column('permission_type', sa.String(length=50), nullable=False, comment='Permission type: storage, notification, external_api'),
    sa.Column('description', sa.Text(), nullable=True, comment='Permission description for users'),
    sa.Column('required', sa.Boolean(), nullable=False, comment='Is this permission mandatory for cat to function'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['cat_id'], ['cats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_permissions_cat_type', 'permissions', ['cat_id', 'permission_type'], unique=False)
    op.create_table('installation_permissions',
    sa.Column('installation_id', sa.UUID(), nullable=False, comment='Installation reference (FK to installations.id)'),
    sa.Column('permission_id', sa.UUID(), nullable=False, comment='Permission reference (FK to permissions.id)'),
    sa.Column('granted', sa.Boolean(), nullable=False, comment='Permission granted status'),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True, comment='When permission was granted (UTC)'),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('installation_id', 'permission_id', name='pk_installation_permissions')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('installation_permissions')
    op.drop_index('ix_permissions_cat_type', table_name='permissions')
    op.drop_table('permissions')
    op.drop_index('ix_installations_user_status', table_name='installations')
    op.drop_index('ix_installations_last_interaction', table_name='installations')
    op.drop_table('installations')
    op.drop_index('ix_cats_status', table_name='cats')
    op.drop_index('ix_cats_developer_status', table_name='cats')
    op.drop_table('cats')
    op.drop_index('ix_users_role_active', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
    
